// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATpL6v0tBZ2Fj2zrC7Hqs4CZop7z_QWHI',
    appId: '1:228133324204:web:346206de183b33e327e609',
    messagingSenderId: '228133324204',
    projectId: 'experience-app-f0d26',
    authDomain: 'experience-app-f0d26.firebaseapp.com',
    storageBucket: 'experience-app-f0d26.firebasestorage.app',
    measurementId: 'G-1TF8P49C8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhb1yJYrDfYZFE4kriKkKUJOI3aihIcpI',
    appId: '1:228133324204:android:8e3966ef1b35909f27e609',
    messagingSenderId: '228133324204',
    projectId: 'experience-app-f0d26',
    storageBucket: 'experience-app-f0d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3OE2-BVtqHZw_CKT2f9wsqlJWBWijgI',
    appId: '1:228133324204:ios:764f2be56ece09c027e609',
    messagingSenderId: '228133324204',
    projectId: 'experience-app-f0d26',
    storageBucket: 'experience-app-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3OE2-BVtqHZw_CKT2f9wsqlJWBWijgI',
    appId: '1:228133324204:ios:764f2be56ece09c027e609',
    messagingSenderId: '228133324204',
    projectId: 'experience-app-f0d26',
    storageBucket: 'experience-app-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATpL6v0tBZ2Fj2zrC7Hqs4CZop7z_QWHI',
    appId: '1:228133324204:web:d353618a11b8956427e609',
    messagingSenderId: '228133324204',
    projectId: 'experience-app-f0d26',
    authDomain: 'experience-app-f0d26.firebaseapp.com',
    storageBucket: 'experience-app-f0d26.firebasestorage.app',
    measurementId: 'G-B9R483H6WD',
  );
}
